
CONTROLLER_RATE: 10                       # rate in Hz

startup_time: 6.0                         # s

max_vel: 1                                # m/s
max_omega: 0.175                          # rad/s

wp_threshold: 0.25                        # distance threshold at which we transition to next waypoint (m)
theta_threshold: rad(pi/8)                # robot theta threshold at which we transition to next waypoint (rad)
time_threshold: 1                         # time threshold about final trajectory time at which we signal last waypoint flag (s)

# controller params
ctrl_tf_state: {"num": [ 0.09520937, -0.09511421], "den": [ 1.0 , -1.90474226,  0.90483742]}
ctrl_tf_state_dot: {"num": [0.02469009], "den": [ 1.0, -0.97530991]}

# localization filter params: AR1-142
positionFilterParams: {"Q": 0.8, "Q_d": 0.8}
thetaFilterParams: {"Q": 0.1, "Q_d": 0.1}

# object offsets
object_offset: {"x": 0.75, "y": 1.2}
